name: Dev CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t go-crud-app:dev .

      - name: Deploy with docker-compose
        run: |
          docker compose down || true
          docker compose up -d --build

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
